### ISSUE TITLE
`betterf.nvim` vs `mini.jump2d`

### ISSUE THREAD

**Issue by savchenko** [jjshoots/betterf.nvim#2]
Would be great to outline main advantages (if any) over the latter. From a quick glance they look remarkably similar.

**Comment by jjshoots** [comment]
Well, this plugin is actually very different from `mini.jump2d`. That plugin uses iterative filtering and allows the user to jump across buffers, `betterf` uses a much simpler way to jump within the buffer. The other thing is that, betterf.nvim runs on nvim >0.5, while mini.jump2d required nvim >0.7.

I don't see the point of advertising "plugin-A is better than plugin-B" as though I'm trying to sell a product. `mini.jump2d` is a much more powerful plugin that does a different thing to what I wanted with `betterf`, you're welcomed to use either and see which you perfer. :)

**Comment by jjshoots** [comment]
I'd also like to point out that this (and `mini.jump2d`) are not the first of its kind of plugins that help with navigation. Lots of other plugins do similar things in slightly different ways. Some examples are [flash.nvim](https://github.com/folke/flash.nvim), [leap.nvim](https://github.com/ggandor/leap.nvim) and [lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim).

**Comment by savchenko** [comment]
@jjshoots , appreciate your suggestions; settled with `flash.nvim` after some (very) painful configuration process.
